# Generated by Django 4.2.15 on 2024-09-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickertagentry',
            options={'ordering': ['sticker', 'user', 'tag']},
        ),
        migrations.AlterField(
            model_name='userentry',
            name='status',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
