# Generated by Django 4.2.15 on 2024-09-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_stickertagentry_options_alter_userentry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickertagentry',
            options={'ordering': ['tag', 'user', 'sticker']},
        ),
    ]
